=== ARCAD-Software/AFS/bundles/server/metadata.rights/schema/rights.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://xml.arcadsoftware.com/1.0.0/rights.xsd"
	xmlns="http://xml.arcadsoftware.com/1.0.0/rights.xsd" 
	elementFormDefault="qualified">

	<xsd:element name="list">
		<xsd:annotation><xsd:documentation><p>List of atomic rights and/or categories of rights.</p>
		<p>Rights are identified by a unique numeric ID. Redefining a right is not a problem as long as the semantics are preserved. These semantics must be defined by an external document. It is generally arranged to reserve ranges of identifiers for specific uses.</p>
		<p>Rights categories are just organizational information used to improve the presentation of rights to the user. Their use is optional, in some cases rights that are not attached to a category will not be presented to the user.</p></xsd:documentation></xsd:annotation>
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="right" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:attribute name="id" type="xsd:positiveInteger" use="required">
						<xsd:annotation><xsd:documentation>Unique identifier determining the value of this right. This is the ID that will be used to manipulate the right.</xsd:documentation></xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="code" type="xsd:string" use="required">
						<xsd:annotation><xsd:documentation>The code defines a "functional" identifier visible to the user but <strong>not translatable</strong>, thus ensuring consistency in the designation of elements regardless of the user's language.</xsd:documentation></xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="category" type="xsd:positiveInteger" use="optional">
						<xsd:annotation><xsd:documentation>Refers to the category to which the right is attached.</xsd:documentation></xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="date" type="xsd:date" use="optional">
						<xsd:annotation><xsd:documentation>Refers to the date the item was last modified.</xsd:documentation></xsd:annotation>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="rightcategory" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:attribute name="id" type="xsd:positiveInteger" use="required">
						<xsd:annotation><xsd:documentation>Identifies a category. This is the value that will be used as a reference in the rights. As for the latter, the ID is unique and must be reserved globally.</xsd:documentation></xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="code" type="xsd:string" use="required">
						<xsd:annotation><xsd:documentation>The code defines a "functional" identifier visible to the user but <strong>not translatable</strong>, thus ensuring consistency in the designation of elements regardless of the user's language.</xsd:documentation></xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="date" type="xsd:date" use="optional">
						<xsd:annotation><xsd:documentation>Refers to the date the item was last modified.</xsd:documentation></xsd:annotation>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== ARCAD-Software/AFS/bundles/server/metadata.server.user/META-INF/rights.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns="http://xml.arcadsoftware.com/1.0.0/rights.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xml.arcadsoftware.com/1.0.0/rights.xsd http://xml.arcadsoftware.com/1.0.0/rights.xsd ">

	<right id="30" category="3" code="user.read"/>
	<right id="31" category="3" code="user.add"/>
	<right id="32" category="3" code="user.edit"/>
	<right id="37" category="3" code="user.profiles"/>
	<right id="51" category="50" code="profile.add"/>
	<right id="52" category="50" code="profile.edit"/>

	<rightcategory id="3" code="user"/>
	<rightcategory id="50" code="profile"/>
	
</list>
